# Generated by Django 3.2.8 on 2021-10-09 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HB', 'Health and beauty'), ('OTHER', 'Other'), ('ELEC', 'Electronics'), ('HOME', 'Home'), ('SPORT', 'Sports and exercise'), ('ENTER', 'Entertainment'), ('FOOD', 'Food'), ('BOOK', 'Books')], default='OTHER', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
